In [20]:
!pip install pandas plotly streamlit openpyxl xlrd

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.13/dist-packages (5.24.1)
Requirement already satisfied: streamlit in /usr/local/lib/python3.13/dist-packages (1.63.0)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.13/dist-packages (3.1.5)
Requirement already satisfied: xlrd in /usr/local/lib/python3.13/dist-packages (2.0.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from plotly) (26.3)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=5.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (8.5.0)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (11.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.9.3)
Requirement already satisfied: protobuf<8,>=5.26.1 in /usr/local/lib/python3.13/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow!=25.0.0,<26,>=7.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (23.0.1)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (4.16.0)
Requirement already satisfied: starlette<2,>=0.46.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (1.6.0)
Requirement already satisfied: uvicorn<1,>=0.30.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.52.4)
Requirement already satisfied: httptools<1,>=0.6.3 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio<5,>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (4.14.2)
Requirement already satisfied: python-multipart<1,>=0.0.10 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets<17,>=12.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous<3,>=2.1.2 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.13/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.13/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2.25.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.13/dist-packages (from anyio<5,>=4.0.0->streamlit) (3.19)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.27->streamlit) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.27->streamlit) (2026.7.22)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.13/dist-packages (from uvicorn<1,>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2026.6.3)

In [21]:
from google.colab import files

archivo_subido = files.upload()

Saving reporteIboca (1).xls to reporteIboca (1) (2).xls

In [22]:
print(archivo_subido.keys())

dict_keys(['reporteIboca (1) (2).xls'])

In [23]:
import os

nombre_archivo = list(archivo_subido.keys())[0]

print("Nombre:", nombre_archivo)
print("Tamaño:", os.path.getsize(nombre_archivo), "bytes")

!file "$nombre_archivo"

Nombre: reporteIboca (1) (2).xls
Tamaño: 13958815 bytes
reporteIboca (1) (2).xls: HTML document, Unicode text, UTF-8 text, with very long lines (4394)

In [24]:
!pip install xlrd

Requirement already satisfied: xlrd in /usr/local/lib/python3.13/dist-packages (2.0.2)

In [25]:
import pandas as pd

nombre_archivo = list(archivo_subido.keys())[0]

tablas = pd.read_html(nombre_archivo)

print("Cantidad de tablas:", len(tablas))

for i, tabla in enumerate(tablas):
    print("Tabla", i, ":", tabla.shape)

Cantidad de tablas: 2
Tabla 0 : (4, 2)
Tabla 1 : (3628, 58)

In [26]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

In [28]:
datos = tablas[1]

print("Tamaño de los datos:", datos.shape)

datos.head()

Tamaño de los datos: (3628, 58)

    Unnamed: 0_level_0       Bolivia                         CDAR          \
          Fecha & Hora   PM2.5 µg/m3                  PM2.5 µg/m3
          Fecha & Hora Concentración NowCast  IBOCA Concentración NowCast
0  2026-01-01 18:00:00            11   11.93   49.7             8    8.87
1  2026-01-01 19:00:00             8    9.99  41.64             5    7.37
2  2026-01-01 20:00:00             5    7.79  32.46             5    6.29
3  2026-01-01 21:00:00             4     5.9  24.57             5    5.78
4  2026-01-01 22:00:00             2    4.43  18.45             4    5.22

         Ciudad BolÃ­var                 ...        Usme      Fontibon  \
             PM2.5 µg/m3                 ... PM2.5 µg/m3   PM2.5 µg/m3
   IBOCA   Concentración NowCast  IBOCA  ...       IBOCA Concentración
0  36.97               3    4.24  17.67  ...       24.11      Sin data
1  30.73               3    3.65  15.22  ...        1.92             3
2  26.22               3    3.59  14.97  ...        1.12             2
3  24.07               3    3.79  15.77  ...        0.79             2
4  21.75               3    3.89  16.19  ...        0.55             2

                             Colina                     Carvajal - Sevillana  \
                        PM2.5 µg/m3                              PM2.5 µg/m3
    NowCast     IBOCA Concentración   NowCast     IBOCA        Concentración
0  Sin data  Sin data      Sin data  Sin data  Sin data             Sin data
1      4.83     20.13      Sin data  Sin data  Sin data             Sin data
2      3.91     16.29      Sin data  Sin data  Sin data             Sin data
3      3.15     13.12      Sin data  Sin data  Sin data             Sin data
4      2.66      11.1      Sin data  Sin data  Sin data             Sin data



    NowCast     IBOCA
0  Sin data  Sin data
1  Sin data  Sin data
2  Sin data  Sin data
3  Sin data  Sin data
4  Sin data  Sin data

[5 rows x 58 columns]

In [29]:
print("Número de columnas:", len(datos.columns))

for i, columna in enumerate(datos.columns):
    print(i, "→", columna)

Número de columnas: 58
0 → ('Unnamed: 0_level_0', 'Fecha & Hora', 'Fecha & Hora')
1 → ('Bolivia', 'PM2.5 µg/m3', 'Concentración')
2 → ('Bolivia', 'PM2.5 µg/m3', 'NowCast')
3 → ('Bolivia', 'PM2.5 µg/m3', 'IBOCA')
4 → ('CDAR', 'PM2.5 µg/m3', 'Concentración')
5 → ('CDAR', 'PM2.5 µg/m3', 'NowCast')
6 → ('CDAR', 'PM2.5 µg/m3', 'IBOCA')
7 → ('Ciudad BolÃ\xadvar', 'PM2.5 µg/m3', 'Concentración')
8 → ('Ciudad BolÃ\xadvar', 'PM2.5 µg/m3', 'NowCast')
9 → ('Ciudad BolÃ\xadvar', 'PM2.5 µg/m3', 'IBOCA')
10 → ('Guaymaral', 'PM2.5 µg/m3', 'Concentración')
11 → ('Guaymaral', 'PM2.5 µg/m3', 'NowCast')
12 → ('Guaymaral', 'PM2.5 µg/m3', 'IBOCA')
13 → ('JazmÃ\xadn', 'PM2.5 µg/m3', 'Concentración')
14 → ('JazmÃ\xadn', 'PM2.5 µg/m3', 'NowCast')
15 → ('JazmÃ\xadn', 'PM2.5 µg/m3', 'IBOCA')
16 → ('Kennedy', 'PM2.5 µg/m3', 'Concentración')
17 → ('Kennedy', 'PM2.5 µg/m3', 'NowCast')
18 → ('Kennedy', 'PM2.5 µg/m3', 'IBOCA')
19 → ('Las Ferias', 'PM2.5 µg/m3', 'Concentración')
20 → ('Las Ferias', 'PM2.5 µg/m3', 'NowCast')
21 → ('Las Ferias', 'PM2.5 µg/m3', 'IBOCA')
22 → ('MinAmbiente', 'PM2.5 µg/m3', 'Concentración')
23 → ('MinAmbiente', 'PM2.5 µg/m3', 'NowCast')
24 → ('MinAmbiente', 'PM2.5 µg/m3', 'IBOCA')
25 → ('MÃ³vil 7ma', 'PM2.5 µg/m3', 'Concentración')
26 → ('MÃ³vil 7ma', 'PM2.5 µg/m3', 'NowCast')
27 → ('MÃ³vil 7ma', 'PM2.5 µg/m3', 'IBOCA')
28 → ('MÃ³vil FontibÃ³n', 'PM2.5 µg/m3', 'Concentración')
29 → ('MÃ³vil FontibÃ³n', 'PM2.5 µg/m3', 'NowCast')
30 → ('MÃ³vil FontibÃ³n', 'PM2.5 µg/m3', 'IBOCA')
31 → ('Puente Aranda', 'PM2.5 µg/m3', 'Concentración')
32 → ('Puente Aranda', 'PM2.5 µg/m3', 'NowCast')
33 → ('Puente Aranda', 'PM2.5 µg/m3', 'IBOCA')
34 → ('San Cristobal', 'PM2.5 µg/m3', 'Concentración')
35 → ('San Cristobal', 'PM2.5 µg/m3', 'NowCast')
36 → ('San Cristobal', 'PM2.5 µg/m3', 'IBOCA')
37 → ('Suba', 'PM2.5 µg/m3', 'Concentración')
38 → ('Suba', 'PM2.5 µg/m3', 'NowCast')
39 → ('Suba', 'PM2.5 µg/m3', 'IBOCA')
40 → ('Tunal', 'PM2.5 µg/m3', 'Concentración')
41 → ('Tunal', 'PM2.5 µg/m3', 'NowCast')
42 → ('Tunal', 'PM2.5 µg/m3', 'IBOCA')
43 → ('Usaquen', 'PM2.5 µg/m3', 'Concentración')
44 → ('Usaquen', 'PM2.5 µg/m3', 'NowCast')
45 → ('Usaquen', 'PM2.5 µg/m3', 'IBOCA')
46 → ('Usme', 'PM2.5 µg/m3', 'Concentración')
47 → ('Usme', 'PM2.5 µg/m3', 'NowCast')
48 → ('Usme', 'PM2.5 µg/m3', 'IBOCA')
49 → ('Fontibon', 'PM2.5 µg/m3', 'Concentración')
50 → ('Fontibon', 'PM2.5 µg/m3', 'NowCast')
51 → ('Fontibon', 'PM2.5 µg/m3', 'IBOCA')
52 → ('Colina', 'PM2.5 µg/m3', 'Concentración')
53 → ('Colina', 'PM2.5 µg/m3', 'NowCast')
54 → ('Colina', 'PM2.5 µg/m3', 'IBOCA')
55 → ('Carvajal - Sevillana', 'PM2.5 µg/m3', 'Concentración')
56 → ('Carvajal - Sevillana', 'PM2.5 µg/m3', 'NowCast')
57 → ('Carvajal - Sevillana', 'PM2.5 µg/m3', 'IBOCA')

In [30]:
pd.set_option("display.max_columns", None)

datos.head(10)

    Unnamed: 0_level_0       Bolivia                         CDAR          \
          Fecha & Hora   PM2.5 µg/m3                  PM2.5 µg/m3
          Fecha & Hora Concentración NowCast  IBOCA Concentración NowCast
0  2026-01-01 18:00:00            11   11.93   49.7             8    8.87
1  2026-01-01 19:00:00             8    9.99  41.64             5    7.37
2  2026-01-01 20:00:00             5    7.79  32.46             5    6.29
3  2026-01-01 21:00:00             4     5.9  24.57             5    5.78
4  2026-01-01 22:00:00             2    4.43  18.45             4    5.22
5  2026-01-01 23:00:00             2    3.35  13.97             3    4.48
6  2026-01-02 00:00:00             2    2.76  11.48             4    4.32
7  2026-01-02 01:00:00             2    2.43  10.12             3    4.05
8  2026-01-02 02:00:00             2    2.26    9.4             4    4.37
9  2026-01-02 03:00:00             4    3.24   13.5             5    4.89

         Ciudad BolÃ­var                    Guaymaral                      \
             PM2.5 µg/m3                  PM2.5 µg/m3
   IBOCA   Concentración NowCast  IBOCA Concentración   NowCast     IBOCA
0  36.97               3    4.24  17.67             4      4.58     19.07
1  30.73               3    3.65  15.22            13  Sin data  Sin data
2  26.22               3    3.59  14.97             8  Sin data  Sin data
3  24.07               3    3.79  15.77            10  Sin data  Sin data
4  21.75               3    3.89  16.19             8  Sin data  Sin data
5  18.67               4    4.01  16.71             7      8.26     34.43
6  18.02               4    4.08  17.01             7      7.63      31.8
7  16.86               3    3.97  16.52            20     13.82     54.62
8  18.21               3    3.92  16.31             6      9.91      41.3
9  20.39               3    3.92  16.32             9      9.45     39.39

        JazmÃ­n                      Kennedy                   Las Ferias  \
    PM2.5 µg/m3                  PM2.5 µg/m3                  PM2.5 µg/m3
  Concentración NowCast  IBOCA Concentración NowCast  IBOCA Concentración
0             3    4.93  20.55            19   15.45  58.05            19
1             5    4.78  19.93             2     3.7  15.43            13
2             7    5.89  24.53             1    2.81   11.7            10
3             4    4.94  20.59             1    2.18   9.08            13
4             4    4.47  18.63             4    3.44  14.32            13
5             5    4.74  19.73             5    4.49   18.7            10
6             5    4.86  20.24             4    4.74  19.75             8
7             5    4.92  20.49             5    5.32  22.18             9
8             3    3.97  16.53             5    5.43  22.61             6
9             3    3.48  14.51             5     5.4  22.51             8

                   MinAmbiente                   MÃ³vil 7ma                 \
                   PM2.5 µg/m3                  PM2.5 µg/m3
  NowCast  IBOCA Concentración NowCast  IBOCA Concentración NowCast  IBOCA
0   15.36  57.86      Sin data    0.44   1.83             2    3.37  14.03
1   14.44  55.92             6   10.68  44.49             4    2.22   9.24
2   12.29   51.4             6    8.34  34.73            11    6.61  27.53
3   12.65  52.15             8    8.17  34.03             6     6.3  26.26
4   13.04  52.98             7    7.58   31.6             1    3.65  15.21
5   11.74  48.91             5    6.29  26.22             3    3.33  13.86
6   10.21  42.56             9    7.65  31.86             3    3.16  13.18
7    9.66  40.27             6    6.82  28.43             3    3.08  12.84
8    8.18   34.1             5    5.91  24.63             1    2.04    8.5
9    8.36  34.82             5    5.46  22.74      Sin data    1.02   4.25

  MÃ³vil FontibÃ³n                Puente Aranda                San Cristobal  \
       PM2.5 µg/m3                  PM2.5 µg/m3                  PM2.5 µg/m3
     Concentración NowCast  IBOCA Concentración NowCast  IBOCA Concentración
0                6    5.88   24.5             4    6.85  28.56             8
1                1    2.67  11.11             5    5.71  23.78             3
2                1    2.12   8.82             4    5.33  22.21             2
3                1     1.7   7.08             3    4.66  19.41             2
4                1    1.39   5.78             4    4.62  19.23             3
5                1    1.38   5.74             7    5.94  24.76             3
6                1    1.44   5.98             6    6.29  26.21             3
7                1     1.5   6.24             5    5.91  24.63             3
8                1    1.49   6.21             5    5.58  23.23             3
9                1    1.56    6.5             6    5.93  24.71             3

                          Suba                        Tunal                 \
                   PM2.5 µg/m3                  PM2.5 µg/m3
  NowCast  IBOCA Concentración NowCast  IBOCA Concentración NowCast  IBOCA
0    7.74  32.24            11    7.61  31.71            11   10.15  42.28
1    5.19  21.64             9    8.36  34.85             7     7.3  30.42
2     3.9  16.25             6    7.18   29.9             3    5.15  21.44
3    3.14   13.1             8    7.58   31.6             4    4.57  19.04
4    3.56  14.82             6    6.79   28.3             6    5.28  22.02
5    3.59  14.94             2     4.4  18.32             9    7.14  29.76
6    3.69  15.36            12     8.2  34.16             6    6.57  27.38
7    3.66  15.24             8     8.1  33.75             8    7.29  30.36
8    3.42  14.25             7    7.55  31.46             6    6.64  27.68
9    3.25  13.53             6    6.78  28.23             3    4.82  20.09

        Usaquen                         Usme                     Fontibon  \
    PM2.5 µg/m3                  PM2.5 µg/m3                  PM2.5 µg/m3
  Concentración NowCast  IBOCA Concentración NowCast  IBOCA Concentración
0      Sin data    0.81   3.38             5    5.79  24.11      Sin data
1             8    9.07  37.79      Sin data    0.46   1.92             3
2             6    7.53  31.37      Sin data    0.27   1.12             2
3             6    6.76  28.18      Sin data    0.19   0.79             2
4             5    5.88  24.51      Sin data    0.13   0.55             2
5            13    9.44  39.34      Sin data    0.11   0.46             3
6            13   11.22  46.76      Sin data    0.09   0.39             3
7            10   10.61  44.22      Sin data    0.09   0.38             2
8            12   11.31  47.11      Sin data    0.39   1.64             2
9             8    9.65  40.22             3    1.97   8.21             3

                             Colina                     Carvajal - Sevillana  \
                        PM2.5 µg/m3                              PM2.5 µg/m3
    NowCast     IBOCA Concentración   NowCast     IBOCA        Concentración
0  Sin data  Sin data      Sin data  Sin data  Sin data             Sin data
1      4.83     20.13      Sin data  Sin data  Sin data             Sin data
2      3.91     16.29      Sin data  Sin data  Sin data             Sin data
3      3.15     13.12      Sin data  Sin data  Sin data             Sin data
4      2.66      11.1      Sin data  Sin data  Sin data             Sin data
5      3.14     13.08      Sin data  Sin data  Sin data             Sin data
6      3.22     13.41      Sin data  Sin data  Sin data             Sin data
7      3.09     12.87      Sin data  Sin data  Sin data             Sin data
8       2.9     12.08      Sin data  Sin data  Sin data             Sin data
9      3.05     12.71      Sin data  Sin data  Sin data             Sin data



    NowCast     IBOCA
0  Sin data  Sin data
1  Sin data  Sin data
2  Sin data  Sin data
3  Sin data  Sin data
4  Sin data  Sin data
5  Sin data  Sin data
6  Sin data  Sin data
7  Sin data  Sin data
8  Sin data  Sin data
9  Sin data  Sin data

In [31]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3628 entries, 0 to 3627
Data columns (total 58 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   (Unnamed: 0_level_0, Fecha & Hora, Fecha & Hora)    3628 non-null   object
 1   (Bolivia, PM2.5 µg/m3, Concentración)               3628 non-null   object
 2   (Bolivia, PM2.5 µg/m3, NowCast)                     3628 non-null   object
 3   (Bolivia, PM2.5 µg/m3, IBOCA)                       3628 non-null   object
 4   (CDAR, PM2.5 µg/m3, Concentración)                  3628 non-null   object
 5   (CDAR, PM2.5 µg/m3, NowCast)                        3628 non-null   object
 6   (CDAR, PM2.5 µg/m3, IBOCA)                          3628 non-null   object
 7   (Ciudad BolÃ­var, PM2.5 µg/m3, Concentración)       3628 non-null   object
 8   (Ciudad BolÃ­var, PM2.5 µg/m3, NowCast)             3628 non-null   object
 9   (Ciudad BolÃ­var, PM2.5 µg/m3, IBOCA)               3628 non-null   object
 10  (Guaymaral, PM2.5 µg/m3, Concentración)             3628 non-null   object
 11  (Guaymaral, PM2.5 µg/m3, NowCast)                   3628 non-null   object
 12  (Guaymaral, PM2.5 µg/m3, IBOCA)                     3628 non-null   object
 13  (JazmÃ­n, PM2.5 µg/m3, Concentración)               3628 non-null   object
 14  (JazmÃ­n, PM2.5 µg/m3, NowCast)                     3628 non-null   object
 15  (JazmÃ­n, PM2.5 µg/m3, IBOCA)                       3628 non-null   object
 16  (Kennedy, PM2.5 µg/m3, Concentración)               3628 non-null   object
 17  (Kennedy, PM2.5 µg/m3, NowCast)                     3628 non-null   object
 18  (Kennedy, PM2.5 µg/m3, IBOCA)                       3628 non-null   object
 19  (Las Ferias, PM2.5 µg/m3, Concentración)            3628 non-null   object
 20  (Las Ferias, PM2.5 µg/m3, NowCast)                  3628 non-null   object
 21  (Las Ferias, PM2.5 µg/m3, IBOCA)                    3628 non-null   object
 22  (MinAmbiente, PM2.5 µg/m3, Concentración)           3628 non-null   object
 23  (MinAmbiente, PM2.5 µg/m3, NowCast)                 3628 non-null   object
 24  (MinAmbiente, PM2.5 µg/m3, IBOCA)                   3628 non-null   object
 25  (MÃ³vil 7ma, PM2.5 µg/m3, Concentración)            3628 non-null   object
 26  (MÃ³vil 7ma, PM2.5 µg/m3, NowCast)                  3628 non-null   object
 27  (MÃ³vil 7ma, PM2.5 µg/m3, IBOCA)                    3628 non-null   object
 28  (MÃ³vil FontibÃ³n, PM2.5 µg/m3, Concentración)      3628 non-null   object
 29  (MÃ³vil FontibÃ³n, PM2.5 µg/m3, NowCast)            3628 non-null   object
 30  (MÃ³vil FontibÃ³n, PM2.5 µg/m3, IBOCA)              3628 non-null   object
 31  (Puente Aranda, PM2.5 µg/m3, Concentración)         3628 non-null   object
 32  (Puente Aranda, PM2.5 µg/m3, NowCast)               3628 non-null   object
 33  (Puente Aranda, PM2.5 µg/m3, IBOCA)                 3628 non-null   object
 34  (San Cristobal, PM2.5 µg/m3, Concentración)         3628 non-null   object
 35  (San Cristobal, PM2.5 µg/m3, NowCast)               3628 non-null   object
 36  (San Cristobal, PM2.5 µg/m3, IBOCA)                 3628 non-null   object
 37  (Suba, PM2.5 µg/m3, Concentración)                  3628 non-null   object
 38  (Suba, PM2.5 µg/m3, NowCast)                        3628 non-null   object
 39  (Suba, PM2.5 µg/m3, IBOCA)                          3628 non-null   object
 40  (Tunal, PM2.5 µg/m3, Concentración)                 3628 non-null   object
 41  (Tunal, PM2.5 µg/m3, NowCast)                       3628 non-null   object
 42  (Tunal, PM2.5 µg/m3, IBOCA)                         3628 non-null   object
 43  (Usaquen, PM2.5 µg/m3, Concentración)               3628 non-null   object
 44  (Usaquen, PM2.5 µg/m3, NowCast)                     3628 non-null   object
 45  (Usaquen, PM2.5 µg/m3, IBOCA)                       3628 non-null   object
 46  (Usme, PM2.5 µg/m3, Concentración)                  3628 non-null   object
 47  (Usme, PM2.5 µg/m3, NowCast)                        3628 non-null   object
 48  (Usme, PM2.5 µg/m3, IBOCA)                          3628 non-null   object
 49  (Fontibon, PM2.5 µg/m3, Concentración)              3628 non-null   object
 50  (Fontibon, PM2.5 µg/m3, NowCast)                    3628 non-null   object
 51  (Fontibon, PM2.5 µg/m3, IBOCA)                      3628 non-null   object
 52  (Colina, PM2.5 µg/m3, Concentración)                3628 non-null   object
 53  (Colina, PM2.5 µg/m3, NowCast)                      3628 non-null   object
 54  (Colina, PM2.5 µg/m3, IBOCA)                        3628 non-null   object
 55  (Carvajal - Sevillana, PM2.5 µg/m3, Concentración)  3628 non-null   object
 56  (Carvajal - Sevillana, PM2.5 µg/m3, NowCast)        3628 non-null   object
 57  (Carvajal - Sevillana, PM2.5 µg/m3, IBOCA)          3628 non-null   object
dtypes: object(58)
memory usage: 1.6+ MB

In [32]:
print(datos.columns)

MultiIndex([(  'Unnamed: 0_level_0', 'Fecha & Hora',  'Fecha & Hora'),
            (             'Bolivia',  'PM2.5 µg/m3', 'Concentración'),
            (             'Bolivia',  'PM2.5 µg/m3',       'NowCast'),
            (             'Bolivia',  'PM2.5 µg/m3',         'IBOCA'),
            (                'CDAR',  'PM2.5 µg/m3', 'Concentración'),
            (                'CDAR',  'PM2.5 µg/m3',       'NowCast'),
            (                'CDAR',  'PM2.5 µg/m3',         'IBOCA'),
            (     'Ciudad BolÃ­var',  'PM2.5 µg/m3', 'Concentración'),
            (     'Ciudad BolÃ­var',  'PM2.5 µg/m3',       'NowCast'),
            (     'Ciudad BolÃ­var',  'PM2.5 µg/m3',         'IBOCA'),
            (           'Guaymaral',  'PM2.5 µg/m3', 'Concentración'),
            (           'Guaymaral',  'PM2.5 µg/m3',       'NowCast'),
            (           'Guaymaral',  'PM2.5 µg/m3',         'IBOCA'),
            (             'JazmÃ­n',  'PM2.5 µg/m3', 'Concentración'),
            (             'JazmÃ­n',  'PM2.5 µg/m3',       'NowCast'),
            (             'JazmÃ­n',  'PM2.5 µg/m3',         'IBOCA'),
            (             'Kennedy',  'PM2.5 µg/m3', 'Concentración'),
            (             'Kennedy',  'PM2.5 µg/m3',       'NowCast'),
            (             'Kennedy',  'PM2.5 µg/m3',         'IBOCA'),
            (          'Las Ferias',  'PM2.5 µg/m3', 'Concentración'),
            (          'Las Ferias',  'PM2.5 µg/m3',       'NowCast'),
            (          'Las Ferias',  'PM2.5 µg/m3',         'IBOCA'),
            (         'MinAmbiente',  'PM2.5 µg/m3', 'Concentración'),
            (         'MinAmbiente',  'PM2.5 µg/m3',       'NowCast'),
            (         'MinAmbiente',  'PM2.5 µg/m3',         'IBOCA'),
            (          'MÃ³vil 7ma',  'PM2.5 µg/m3', 'Concentración'),
            (          'MÃ³vil 7ma',  'PM2.5 µg/m3',       'NowCast'),
            (          'MÃ³vil 7ma',  'PM2.5 µg/m3',         'IBOCA'),
            (    'MÃ³vil FontibÃ³n',  'PM2.5 µg/m3', 'Concentración'),
            (    'MÃ³vil FontibÃ³n',  'PM2.5 µg/m3',       'NowCast'),
            (    'MÃ³vil FontibÃ³n',  'PM2.5 µg/m3',         'IBOCA'),
            (       'Puente Aranda',  'PM2.5 µg/m3', 'Concentración'),
            (       'Puente Aranda',  'PM2.5 µg/m3',       'NowCast'),
            (       'Puente Aranda',  'PM2.5 µg/m3',         'IBOCA'),
            (       'San Cristobal',  'PM2.5 µg/m3', 'Concentración'),
            (       'San Cristobal',  'PM2.5 µg/m3',       'NowCast'),
            (       'San Cristobal',  'PM2.5 µg/m3',         'IBOCA'),
            (                'Suba',  'PM2.5 µg/m3', 'Concentración'),
            (                'Suba',  'PM2.5 µg/m3',       'NowCast'),
            (                'Suba',  'PM2.5 µg/m3',         'IBOCA'),
            (               'Tunal',  'PM2.5 µg/m3', 'Concentración'),
            (               'Tunal',  'PM2.5 µg/m3',       'NowCast'),
            (               'Tunal',  'PM2.5 µg/m3',         'IBOCA'),
            (             'Usaquen',  'PM2.5 µg/m3', 'Concentración'),
            (             'Usaquen',  'PM2.5 µg/m3',       'NowCast'),
            (             'Usaquen',  'PM2.5 µg/m3',         'IBOCA'),
            (                'Usme',  'PM2.5 µg/m3', 'Concentración'),
            (                'Usme',  'PM2.5 µg/m3',       'NowCast'),
            (                'Usme',  'PM2.5 µg/m3',         'IBOCA'),
            (            'Fontibon',  'PM2.5 µg/m3', 'Concentración'),
            (            'Fontibon',  'PM2.5 µg/m3',       'NowCast'),
            (            'Fontibon',  'PM2.5 µg/m3',         'IBOCA'),
            (              'Colina',  'PM2.5 µg/m3', 'Concentración'),
            (              'Colina',  'PM2.5 µg/m3',       'NowCast'),
            (              'Colina',  'PM2.5 µg/m3',         'IBOCA'),
            ('Carvajal - Sevillana',  'PM2.5 µg/m3', 'Concentración'),
            ('Carvajal - Sevillana',  'PM2.5 µg/m3',       'NowCast'),
            ('Carvajal - Sevillana',  'PM2.5 µg/m3',         'IBOCA')],
           )

In [33]:
print(type(datos.columns))

<class 'pandas.core.indexes.multi.MultiIndex'>

In [35]:
df = datos.copy()

In [36]:
print(df.iloc[:, 0].head(20))

0     2026-01-01 18:00:00
1     2026-01-01 19:00:00
2     2026-01-01 20:00:00
3     2026-01-01 21:00:00
4     2026-01-01 22:00:00
5     2026-01-01 23:00:00
6     2026-01-02 00:00:00
7     2026-01-02 01:00:00
8     2026-01-02 02:00:00
9     2026-01-02 03:00:00
10    2026-01-02 04:00:00
11    2026-01-02 05:00:00
12    2026-01-02 06:00:00
13    2026-01-02 07:00:00
14    2026-01-02 08:00:00
15    2026-01-02 09:00:00
16    2026-01-02 10:00:00
17    2026-01-02 11:00:00
18    2026-01-02 12:00:00
19    2026-01-02 13:00:00
Name: (Unnamed: 0_level_0, Fecha & Hora, Fecha & Hora), dtype: object

In [37]:
df["Fecha"] = pd.to_datetime(
    df.iloc[:, 0],
    errors="coerce"
)

print(df["Fecha"].head())

0   2026-01-01 18:00:00
1   2026-01-01 19:00:00
2   2026-01-01 20:00:00
3   2026-01-01 21:00:00
4   2026-01-01 22:00:00
Name: Fecha, dtype: datetime64[ns]

In [38]:
print("Fechas reconocidas:", df["Fecha"].notna().sum())

Fechas reconocidas: 3625

In [42]:
df["Hora"] = df["Fecha"].dt.hour

df["Dia"] = df["Fecha"].dt.date

df["Mes"] = df["Fecha"].dt.month

df["Dia_semana"] = df["Fecha"].dt.day_name()
df[["Fecha", "Hora", "Dia", "Mes", "Dia_semana"]].head()

                Fecha  Hora         Dia  Mes Dia_semana


0 2026-01-01 18:00:00  18.0  2026-01-01  1.0   Thursday
1 2026-01-01 19:00:00  19.0  2026-01-01  1.0   Thursday
2 2026-01-01 20:00:00  20.0  2026-01-01  1.0   Thursday
3 2026-01-01 21:00:00  21.0  2026-01-01  1.0   Thursday
4 2026-01-01 22:00:00  22.0  2026-01-01  1.0   Thursday

In [43]:
for i, columna in enumerate(datos.columns):
    print(i, "→", columna)

0 → ('Unnamed: 0_level_0', 'Fecha & Hora', 'Fecha & Hora')
1 → ('Bolivia', 'PM2.5 µg/m3', 'Concentración')
2 → ('Bolivia', 'PM2.5 µg/m3', 'NowCast')
3 → ('Bolivia', 'PM2.5 µg/m3', 'IBOCA')
4 → ('CDAR', 'PM2.5 µg/m3', 'Concentración')
5 → ('CDAR', 'PM2.5 µg/m3', 'NowCast')
6 → ('CDAR', 'PM2.5 µg/m3', 'IBOCA')
7 → ('Ciudad BolÃ\xadvar', 'PM2.5 µg/m3', 'Concentración')
8 → ('Ciudad BolÃ\xadvar', 'PM2.5 µg/m3', 'NowCast')
9 → ('Ciudad BolÃ\xadvar', 'PM2.5 µg/m3', 'IBOCA')
10 → ('Guaymaral', 'PM2.5 µg/m3', 'Concentración')
11 → ('Guaymaral', 'PM2.5 µg/m3', 'NowCast')
12 → ('Guaymaral', 'PM2.5 µg/m3', 'IBOCA')
13 → ('JazmÃ\xadn', 'PM2.5 µg/m3', 'Concentración')
14 → ('JazmÃ\xadn', 'PM2.5 µg/m3', 'NowCast')
15 → ('JazmÃ\xadn', 'PM2.5 µg/m3', 'IBOCA')
16 → ('Kennedy', 'PM2.5 µg/m3', 'Concentración')
17 → ('Kennedy', 'PM2.5 µg/m3', 'NowCast')
18 → ('Kennedy', 'PM2.5 µg/m3', 'IBOCA')
19 → ('Las Ferias', 'PM2.5 µg/m3', 'Concentración')
20 → ('Las Ferias', 'PM2.5 µg/m3', 'NowCast')
21 → ('Las Ferias', 'PM2.5 µg/m3', 'IBOCA')
22 → ('MinAmbiente', 'PM2.5 µg/m3', 'Concentración')
23 → ('MinAmbiente', 'PM2.5 µg/m3', 'NowCast')
24 → ('MinAmbiente', 'PM2.5 µg/m3', 'IBOCA')
25 → ('MÃ³vil 7ma', 'PM2.5 µg/m3', 'Concentración')
26 → ('MÃ³vil 7ma', 'PM2.5 µg/m3', 'NowCast')
27 → ('MÃ³vil 7ma', 'PM2.5 µg/m3', 'IBOCA')
28 → ('MÃ³vil FontibÃ³n', 'PM2.5 µg/m3', 'Concentración')
29 → ('MÃ³vil FontibÃ³n', 'PM2.5 µg/m3', 'NowCast')
30 → ('MÃ³vil FontibÃ³n', 'PM2.5 µg/m3', 'IBOCA')
31 → ('Puente Aranda', 'PM2.5 µg/m3', 'Concentración')
32 → ('Puente Aranda', 'PM2.5 µg/m3', 'NowCast')
33 → ('Puente Aranda', 'PM2.5 µg/m3', 'IBOCA')
34 → ('San Cristobal', 'PM2.5 µg/m3', 'Concentración')
35 → ('San Cristobal', 'PM2.5 µg/m3', 'NowCast')
36 → ('San Cristobal', 'PM2.5 µg/m3', 'IBOCA')
37 → ('Suba', 'PM2.5 µg/m3', 'Concentración')
38 → ('Suba', 'PM2.5 µg/m3', 'NowCast')
39 → ('Suba', 'PM2.5 µg/m3', 'IBOCA')
40 → ('Tunal', 'PM2.5 µg/m3', 'Concentración')
41 → ('Tunal', 'PM2.5 µg/m3', 'NowCast')
42 → ('Tunal', 'PM2.5 µg/m3', 'IBOCA')
43 → ('Usaquen', 'PM2.5 µg/m3', 'Concentración')
44 → ('Usaquen', 'PM2.5 µg/m3', 'NowCast')
45 → ('Usaquen', 'PM2.5 µg/m3', 'IBOCA')
46 → ('Usme', 'PM2.5 µg/m3', 'Concentración')
47 → ('Usme', 'PM2.5 µg/m3', 'NowCast')
48 → ('Usme', 'PM2.5 µg/m3', 'IBOCA')
49 → ('Fontibon', 'PM2.5 µg/m3', 'Concentración')
50 → ('Fontibon', 'PM2.5 µg/m3', 'NowCast')
51 → ('Fontibon', 'PM2.5 µg/m3', 'IBOCA')
52 → ('Colina', 'PM2.5 µg/m3', 'Concentración')
53 → ('Colina', 'PM2.5 µg/m3', 'NowCast')
54 → ('Colina', 'PM2.5 µg/m3', 'IBOCA')
55 → ('Carvajal - Sevillana', 'PM2.5 µg/m3', 'Concentración')
56 → ('Carvajal - Sevillana', 'PM2.5 µg/m3', 'NowCast')
57 → ('Carvajal - Sevillana', 'PM2.5 µg/m3', 'IBOCA')

In [44]:
print(df.iloc[:, 0].head(20))

0     2026-01-01 18:00:00
1     2026-01-01 19:00:00
2     2026-01-01 20:00:00
3     2026-01-01 21:00:00
4     2026-01-01 22:00:00
5     2026-01-01 23:00:00
6     2026-01-02 00:00:00
7     2026-01-02 01:00:00
8     2026-01-02 02:00:00
9     2026-01-02 03:00:00
10    2026-01-02 04:00:00
11    2026-01-02 05:00:00
12    2026-01-02 06:00:00
13    2026-01-02 07:00:00
14    2026-01-02 08:00:00
15    2026-01-02 09:00:00
16    2026-01-02 10:00:00
17    2026-01-02 11:00:00
18    2026-01-02 12:00:00
19    2026-01-02 13:00:00
Name: (Unnamed: 0_level_0, Fecha & Hora, Fecha & Hora), dtype: object

In [46]:
df["Fecha"] = pd.to_datetime(
    df.iloc[:, 0],
    errors="coerce"
)

print(df["Fecha"].head())
print("Fechas reconocidas:", df["Fecha"].notna().sum())

0   2026-01-01 18:00:00
1   2026-01-01 19:00:00
2   2026-01-01 20:00:00
3   2026-01-01 21:00:00
4   2026-01-01 22:00:00
Name: Fecha, dtype: datetime64[ns]
Fechas reconocidas: 3625

In [48]:
# ==========================================
# PASO 2: LIMPIAR LOS DATOS
# ==========================================

# Convertimos la fecha correctamente
df["Fecha"] = pd.to_datetime(
    df.iloc[:, 0],
    errors="coerce"
)

# Reemplazamos "Sin data" por valores vacíos
df = df.replace("Sin data", np.nan)

# Lista para guardar los datos organizados
datos_limpios = []

# Recorremos todas las columnas
for columna in df.columns[1:]:

    # Obtenemos el nombre de la estación
    estacion = columna[0]

    # Obtenemos el tipo de dato
    tipo = columna[2]

    # Solo nos interesa Concentración
    if tipo == "Concentración":

        # Creamos una pequeña tabla
        temporal = pd.DataFrame({
            "Fecha": df["Fecha"],
            "Estacion": estacion,
            "PM2.5": pd.to_numeric(df[columna], errors="coerce")
        })

        # La agregamos a la lista
        datos_limpios.append(temporal)


# Unimos todas las estaciones
df_pm25 = pd.concat(datos_limpios, ignore_index=True)


# Eliminamos datos que no tengan fecha o PM2.5
df_pm25 = df_pm25.dropna(
    subset=["Fecha", "PM2.5"]
)


# ==========================================
# REVISAR EL RESULTADO
# ==========================================

print("Tamaño de la nueva tabla:")
print(df_pm25.shape)

print("\nPrimeras filas:")
display(df_pm25.head(10))

print("\nEstaciones encontradas:")
print(df_pm25["Estacion"].unique())

print("\nInformación:")
print(df_pm25.info())

Tamaño de la nueva tabla:
(58735, 3)

Primeras filas:

                Fecha Estacion  PM2.5
0 2026-01-01 18:00:00  Bolivia   11.0
1 2026-01-01 19:00:00  Bolivia    8.0
2 2026-01-01 20:00:00  Bolivia    5.0
3 2026-01-01 21:00:00  Bolivia    4.0
4 2026-01-01 22:00:00  Bolivia    2.0
5 2026-01-01 23:00:00  Bolivia    2.0
6 2026-01-02 00:00:00  Bolivia    2.0
7 2026-01-02 01:00:00  Bolivia    2.0
8 2026-01-02 02:00:00  Bolivia    2.0
9 2026-01-02 03:00:00  Bolivia    4.0

Estaciones encontradas:
['Bolivia' 'CDAR' 'Ciudad BolÃ\xadvar' 'Guaymaral' 'JazmÃ\xadn' 'Kennedy'
 'Las Ferias' 'MinAmbiente' 'MÃ³vil 7ma' 'MÃ³vil FontibÃ³n'
 'Puente Aranda' 'San Cristobal' 'Suba' 'Tunal' 'Usaquen' 'Usme'
 'Fontibon' 'Colina' 'Carvajal - Sevillana']

Información:
<class 'pandas.core.frame.DataFrame'>
Index: 58735 entries, 0 to 68848
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Fecha     58735 non-null  datetime64[ns]
 1   Estacion  58735 non-null  object
 2   PM2.5     58735 non-null  float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 1.8+ MB
None

In [49]:
# ==========================================
# PASO 3: INDICADORES DEL DASHBOARD
# ==========================================

# 1. Promedio general de PM2.5
promedio_pm25 = df_pm25["PM2.5"].mean()

# 2. Valor máximo registrado
maximo_pm25 = df_pm25["PM2.5"].max()

# 3. Registro donde ocurrió el máximo
registro_maximo = df_pm25.loc[
    df_pm25["PM2.5"].idxmax()
]

# 4. Promedio de PM2.5 por estación
promedio_estacion = (
    df_pm25
    .groupby("Estacion")["PM2.5"]
    .mean()
    .sort_values(ascending=False)
)

# 5. Estación con mayor promedio
estacion_mayor = promedio_estacion.index[0]

# 6. Valor promedio de esa estación
valor_estacion_mayor = promedio_estacion.iloc[0]


# ==========================================
# MOSTRAR LOS RESULTADOS
# ==========================================

print("===================================")
print("       INDICADORES PM2.5")
print("===================================")

print(
    "Promedio general de PM2.5:",
    round(promedio_pm25, 2),
    "µg/m³"
)

print(
    "Máximo registrado:",
    maximo_pm25,
    "µg/m³"
)

print(
    "Estación con mayor promedio:",
    estacion_mayor
)

print(
    "Promedio de esa estación:",
    round(valor_estacion_mayor, 2),
    "µg/m³"
)

print(
    "Fecha y hora del máximo:",
    registro_maximo["Fecha"]
)

===================================
       INDICADORES PM2.5
===================================
Promedio general de PM2.5: 14.19 µg/m³
Máximo registrado: 176.0 µg/m³
Estación con mayor promedio: CDAR
Promedio de esa estación: 21.72 µg/m³
Fecha y hora del máximo: 2026-03-21 01:00:00

In [50]:
# ==========================================
# PASO 4: PROMEDIO DE PM2.5 POR ESTACIÓN
# ==========================================

# Calculamos el promedio de PM2.5 para cada estación
promedio_estacion = (
    df_pm25
    .groupby("Estacion")["PM2.5"]
    .mean()
    .sort_values(ascending=False)
)

# Mostramos los resultados
print("PROMEDIO DE PM2.5 POR ESTACIÓN:")
print(promedio_estacion.round(2))

PROMEDIO DE PM2.5 POR ESTACIÓN:
Estacion
CDAR                    21.72
Kennedy                 17.09
MÃ³vil 7ma              16.05
MinAmbiente             15.00
Usaquen                 14.88
Fontibon                14.71
MÃ³vil FontibÃ³n        14.51
Usme                    14.49
Las Ferias              14.36
Puente Aranda           13.54
Guaymaral               13.48
JazmÃ­n                 13.43
Suba                    12.99
San Cristobal           12.53
Bolivia                 12.26
Ciudad BolÃ­var         11.74
Tunal                   11.59
Carvajal - Sevillana    11.34
Colina                   9.66
Name: PM2.5, dtype: float64

In [51]:
# ==========================================
# GRÁFICO: PM2.5 POR ESTACIÓN
# ==========================================

fig = px.bar(
    x=promedio_estacion.index,
    y=promedio_estacion.values,
    labels={
        "x": "Estación",
        "y": "PM2.5 (µg/m³)"
    },
    title="Promedio de PM2.5 por estación"
)

fig.update_layout(
    xaxis_tickangle=-45
)

fig.show()

In [52]:
# ==========================================
# PASO 5: PM2.5 A LO LARGO DEL TIEMPO
# ==========================================

# Calculamos el promedio de PM2.5 para cada fecha
promedio_fecha = (
    df_pm25
    .groupby("Fecha")["PM2.5"]
    .mean()
    .reset_index()
)

# ==========================================
# CREAR EL GRÁFICO
# ==========================================

fig = px.line(
    promedio_fecha,
    x="Fecha",
    y="PM2.5",
    labels={
        "Fecha": "Fecha y hora",
        "PM2.5": "PM2.5 (µg/m³)"
    },
    title="Evolución del PM2.5 a lo largo del tiempo"
)

fig.show()

In [55]:
# ==========================================
# PASO 6: PM2.5 SEGÚN LA HORA
# ==========================================

# Creamos la columna Hora a partir de Fecha
df_pm25["Hora"] = df_pm25["Fecha"].dt.hour


# Calculamos el promedio de PM2.5 para cada hora
promedio_hora = (
    df_pm25
    .groupby("Hora")["PM2.5"]
    .mean()
    .reset_index()
)

# Ordenamos las horas
promedio_hora = promedio_hora.sort_values("Hora")


# ==========================================
# MOSTRAR LOS RESULTADOS
# ==========================================

print("PROMEDIO DE PM2.5 SEGÚN LA HORA:")

display(promedio_hora.round(2))


# ==========================================
# CREAR EL GRÁFICO
# ==========================================

fig = px.line(
    promedio_hora,
    x="Hora",
    y="PM2.5",
    markers=True,
    labels={
        "Hora": "Hora del día",
        "PM2.5": "PM2.5 (µg/m³)"
    },
    title="Promedio de PM2.5 según la hora del día"
)

fig.show()

PROMEDIO DE PM2.5 SEGÚN LA HORA:

    Hora  PM2.5
0      0  13.03
1      1  13.30
2      2  13.13
3      3  12.99
4      4  13.25
5      5  13.84
6      6  15.19
7      7  16.87
8      8  18.48
9      9  18.51
10    10  17.57
11    11  16.08
12    12  14.77
13    13  14.06
14    14  13.70
15    15  13.17
16    16  13.25
17    17  12.81
18    18  12.32
19    19  12.12
20    20  12.55
21    21  13.02
22    22  13.22
23    23  13.23

In [56]:
# ==========================================
# PASO 7: PM2.5 POR DÍA DE LA SEMANA
# ==========================================

# Creamos la columna con el día de la semana
df_pm25["Dia_semana"] = df_pm25["Fecha"].dt.day_name()


# Calculamos el promedio de PM2.5 para cada día
promedio_dia = (
    df_pm25
    .groupby("Dia_semana")["PM2.5"]
    .mean()
    .reset_index()
)


# ==========================================
# ORDENAR LOS DÍAS CORRECTAMENTE
# ==========================================

orden_dias = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
]

promedio_dia["Dia_semana"] = pd.Categorical(
    promedio_dia["Dia_semana"],
    categories=orden_dias,
    ordered=True
)

promedio_dia = promedio_dia.sort_values("Dia_semana")


# ==========================================
# MOSTRAR LOS RESULTADOS
# ==========================================

print("PROMEDIO DE PM2.5 POR DÍA DE LA SEMANA:")

display(promedio_dia.round(2))


# ==========================================
# CREAR EL GRÁFICO
# ==========================================

fig = px.bar(
    promedio_dia,
    x="Dia_semana",
    y="PM2.5",
    labels={
        "Dia_semana": "Día de la semana",
        "PM2.5": "PM2.5 (µg/m³)"
    },
    title="Promedio de PM2.5 por día de la semana"
)

fig.show()

PROMEDIO DE PM2.5 POR DÍA DE LA SEMANA:

  Dia_semana  PM2.5
1     Monday  13.30
5    Tuesday  16.25
6  Wednesday  15.40
4   Thursday  15.28
0     Friday  14.37
2   Saturday  13.40
3     Sunday  11.28

In [57]:
# ==========================================
# PASO 8: MAYOR Y MENOR PM2.5 POR ESTACIÓN
# ==========================================

# Calculamos el promedio de PM2.5 por estación
promedio_estacion = (
    df_pm25
    .groupby("Estacion")["PM2.5"]
    .mean()
    .sort_values(ascending=False)
)


# ==========================================
# ESTACIÓN CON MAYOR PROMEDIO
# ==========================================

estacion_mayor = promedio_estacion.idxmax()
valor_mayor = promedio_estacion.max()


# ==========================================
# ESTACIÓN CON MENOR PROMEDIO
# ==========================================

estacion_menor = promedio_estacion.idxmin()
valor_menor = promedio_estacion.min()


# ==========================================
# MOSTRAR RESULTADOS
# ==========================================

print("===================================")
print("   ANÁLISIS POR ESTACIÓN")
print("===================================")

print(
    "Estación con mayor promedio:",
    estacion_mayor
)

print(
    "Promedio más alto:",
    round(valor_mayor, 2),
    "µg/m³"
)

print()

print(
    "Estación con menor promedio:",
    estacion_menor
)

print(
    "Promedio más bajo:",
    round(valor_menor, 2),
    "µg/m³"
)

===================================
   ANÁLISIS POR ESTACIÓN
===================================
Estación con mayor promedio: CDAR
Promedio más alto: 21.72 µg/m³

Estación con menor promedio: Colina
Promedio más bajo: 9.66 µg/m³

In [58]:
# ==========================================
# PASO 9: SELECCIONAR UNA ESTACIÓN
# ==========================================

# Lista de estaciones disponibles
estaciones = sorted(df_pm25["Estacion"].unique())

print("ESTACIONES DISPONIBLES:")

for i, estacion in enumerate(estaciones, start=1):
    print(i, "-", estacion)


# ==========================================
# ELEGIR UNA ESTACIÓN
# ==========================================

numero = int(input("\nEscribe el número de la estación que quieres consultar: "))

estacion_seleccionada = estaciones[numero - 1]

print("\nEstación seleccionada:", estacion_seleccionada)


# ==========================================
# FILTRAR LOS DATOS
# ==========================================

datos_estacion = df_pm25[
    df_pm25["Estacion"] == estacion_seleccionada
].copy()


print("\nCantidad de registros:")
print(len(datos_estacion))

print("\nPrimeros registros:")
display(datos_estacion.head(10))

ESTACIONES DISPONIBLES:
1 - Bolivia
2 - CDAR
3 - Carvajal - Sevillana
4 - Ciudad BolÃ­var
5 - Colina
6 - Fontibon
7 - Guaymaral
8 - JazmÃ­n
9 - Kennedy
10 - Las Ferias
11 - MinAmbiente
12 - MÃ³vil 7ma
13 - MÃ³vil FontibÃ³n
14 - Puente Aranda
15 - San Cristobal
16 - Suba
17 - Tunal
18 - Usaquen
19 - Usme

Escribe el número de la estación que quieres consultar: 2

Estación seleccionada: CDAR

Cantidad de registros:
3408

Primeros registros:

                   Fecha Estacion  PM2.5  Hora Dia_semana
3628 2026-01-01 18:00:00     CDAR    8.0    18   Thursday
3629 2026-01-01 19:00:00     CDAR    5.0    19   Thursday
3630 2026-01-01 20:00:00     CDAR    5.0    20   Thursday
3631 2026-01-01 21:00:00     CDAR    5.0    21   Thursday
3632 2026-01-01 22:00:00     CDAR    4.0    22   Thursday
3633 2026-01-01 23:00:00     CDAR    3.0    23   Thursday
3634 2026-01-02 00:00:00     CDAR    4.0     0     Friday
3635 2026-01-02 01:00:00     CDAR    3.0     1     Friday
3636 2026-01-02 02:00:00     CDAR    4.0     2     Friday
3637 2026-01-02 03:00:00     CDAR    5.0     3     Friday

In [59]:
# ==========================================
# PASO 10: GRÁFICA DE LA ESTACIÓN
# ==========================================

fig = px.line(
    datos_estacion,
    x="Fecha",
    y="PM2.5",
    labels={
        "Fecha": "Fecha y hora",
        "PM2.5": "PM2.5 (µg/m³)"
    },
    title=f"Evolución del PM2.5 - {estacion_seleccionada}"
)

fig.show()

In [60]:
# ==========================================
# PASO 11: RANKING DE ESTACIONES
# ==========================================

# Ordenamos las estaciones de mayor a menor
ranking_estaciones = (
    df_pm25
    .groupby("Estacion")["PM2.5"]
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)

# Agregamos la posición del ranking
ranking_estaciones["Posición"] = range(
    1,
    len(ranking_estaciones) + 1
)

# Organizamos las columnas
ranking_estaciones = ranking_estaciones[
    ["Posición", "Estacion", "PM2.5"]
]


# ==========================================
# MOSTRAR EL RANKING
# ==========================================

print("RANKING DE ESTACIONES SEGÚN PROMEDIO DE PM2.5:")

display(
    ranking_estaciones.round(2)
)

RANKING DE ESTACIONES SEGÚN PROMEDIO DE PM2.5:

    Posición              Estacion  PM2.5
0          1                  CDAR  21.72
1          2               Kennedy  17.09
2          3            MÃ³vil 7ma  16.05
3          4           MinAmbiente  15.00
4          5               Usaquen  14.88
5          6              Fontibon  14.71
6          7      MÃ³vil FontibÃ³n  14.51
7          8                  Usme  14.49
8          9            Las Ferias  14.36
9         10         Puente Aranda  13.54
10        11             Guaymaral  13.48
11        12               JazmÃ­n  13.43
12        13                  Suba  12.99
13        14         San Cristobal  12.53
14        15               Bolivia  12.26
15        16       Ciudad BolÃ­var  11.74
16        17                 Tunal  11.59
17        18  Carvajal - Sevillana  11.34
18        19                Colina   9.66